### ISSUE TITLE
getting error graphql/language 

### ISSUE THREAD

**Issue by veerjainATgmail** [apollographql/meteor-starter-kit#18]
20160710-08:49:29.137(5.5)? (STDERR) C:\Users\mjain\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x
_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
20160710-08:49:29.139(5.5)? (STDERR)                                           throw(ex);
20160710-08:49:29.140(5.5)? (STDERR)                                                 ^
20160710-08:49:29.140(5.5)? (STDERR) Error: Cannot find module 'graphql/language'
20160710-08:49:29.141(5.5)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
20160710-08:49:29.141(5.5)? (STDERR)     at Function.Module._load (module.js:280:25)
20160710-08:49:29.142(5.5)? (STDERR)     at Module.require (module.js:364:17)
20160710-08:49:29.142(5.5)? (STDERR)     at require (module.js:380:17)
20160710-08:49:29.143(5.5)? (STDERR)     at Object.<anonymous> 

anyone faced the same issue?

**Comment by TimMikeladze** [comment]
@veerjainATgmail @stubailo This can be closed, resolved by #19
