### ISSUE TITLE
How to control reactivity?

### ISSUE THREAD

**Issue by trusktr** [apollographql/meteor-starter-kit#21]
Meteor has a characteristic where any update causes reactive updates as soon as possible. Sometimes, this is too much, and can [cause jank](https://forums.meteor.com/t/jank-free-animation-in-meteor/26217), especially when updates are unpredictable and from multiple clients.

How would we control the rate of reactive updates in this Apollo GraphQL example? For example, how would we have updates at most once per second, no faster?

**Comment by stubailo** [comment]
In GraphQL, there is currently no model for server push at all, so this problem simply doesn't come up. In the case where many queries are sent at once, you can turn on query batching to make sure they are all handled as one unit: http://docs.apollostack.com/apollo-client/network.html#query-batching

**Comment by xavcz** [comment]
Hey @trusktr!

There are now several ways to control the reactivity, I'm pointing you out to the docs that will be better than a long speech ☺️

Via polling / refetch or subscriptions: http://dev.apollodata.com/react/receiving-updates.html
By controlling the store: http://dev.apollodata.com/react/cache-updates.html

And you can of course still use Meteor data layer alongside with Apollo 👍
