### ISSUE TITLE
apollo server is not a function

### ISSUE THREAD

**Issue by jamalazza** [apollographql/meteor-starter-kit#25]
Hi there,
thank you for your great work
after installing apollo for meteor I get the error below

**I'm running windows 10**
any advise ?????

E:\projets\meteor\test>meteor --version
Meteor 1.4.0.1

E:\projets\meteor\test>node -v
v6.4.0

E:\projets\meteor\test>npm -v
3.10.7

E:\projets\meteor\test>meteor
[[[[[ ~\E\projets\meteor\test ]]]]]

=> Started proxy.
=> Started MongoDB.
W20160817-09:13:51.899(1)? (STDERR) WARNING: npm peer requirements (for apollo) not installed:
W20160817-09:13:52.008(1)? (STDERR)  - apollo-server@0.2.5 installed, apollo-server@^0.1.1 needed
W20160817-09:13:52.011(1)? (STDERR) 
W20160817-09:13:52.013(1)? (STDERR) Read more about installing npm peer dependencies:
W20160817-09:13:52.014(1)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20160817-09:13:52.016(1)? (STDERR) 
W20160817-09:13:52.040(1)? (STDERR) C:\Users\jamal\AppData\Local.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20160817-09:13:52.042(1)? (STDERR)                                             throw(ex);
W20160817-09:13:52.043(1)? (STDERR)                                             ^
W20160817-09:13:52.045(1)? (STDERR) 
W20160817-09:13:52.046(1)? (STDERR) TypeError: apolloServer is not a function
W20160817-09:13:52.047(1)? (STDERR)     at createApolloServer (meteor://�app/packages/apollo/main-server.js:21:34)
W20160817-09:13:52.049(1)? (STDERR)     at meteorInstall.server.server.js (meteor://�app/server/server.js:5:1)
W20160817-09:13:52.050(1)? (STDERR)     at fileEvaluate (meteor://�app/packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160817-09:13:52.052(1)? (STDERR)     at require (meteor://�app/packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160817-09:13:52.053(1)? (STDERR)     at E:\projets\meteor\test.meteor\local\build\programs\server\app\app.js:92:1
W20160817-09:13:52.055(1)? (STDERR)     at E:\projets\meteor\test.meteor\local\build\programs\server\boot.js:297:10
W20160817-09:13:52.057(1)? (STDERR)     at Array.forEach (native)
W20160817-09:13:52.058(1)? (STDERR)     at Function._.each._.forEach (C:\Users\jamal\AppData\Local.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\server-lib\node_m
odules\underscore\underscore.js:79:11)
W20160817-09:13:52.060(1)? (STDERR)     at E:\projets\meteor\test.meteor\local\build\programs\server\boot.js:133:5
=> Exited with code: 1

**Comment by helfer** [comment]
@jamalazza the warning says that you should install apollo-server 0.1.x, currently you have 0.2.5 installed.

**Comment by xavcz** [comment]
Seems that we can close this 🙂
