### ISSUE TITLE
npm error missing: graphql-typings

### ISSUE THREAD

**Issue by Digital-Thor** [apollographql/meteor-starter-kit#30]
Not sure what this error will affect or whether I can still use the kit.  

```
> meteor npm install
npm WARN graphql-tools@0.6.6 requires a peer of graphql-typings@^0.0.1-beta-2 but none was installed.

> npm ls
npm ERR! missing: graphql-typings@^0.0.1-beta-2, required by graphql-tools@0.6.6
```

I'm using Windows 7 (64 bit). 

```
> meteor --version
Meteor 1.3.4.1
```

**Comment by stubailo** [comment]
Missing peer deps should be a warning, not an error - did you try "meteor npm ls"?

**Comment by Digital-Thor** [comment]
Thanks. Response seems similar:
```
> meteor npm ls
npm ERR! peer dep missing: graphql-typings@^0.0.1-beta-2, required by graphql-tools@0.6.6
```
So what's the impact of ignoring this?

**Comment by stubailo** [comment]
Shouldn't be one.... peer deps are often used for optional stuff. Maybe @helfer can help us understand why that peer dep exists though.

**Comment by helfer** [comment]
If you're not using typescript you can safely ignore that error. I'm thinking maybe we should move all typings dependencies to typings or into proper dependencies. cc @DxCx

**Comment by Digital-Thor** [comment]
Okay.  Thanks.  Just stepping into Apollo and trying to ensure that I've got a solid base environment.  Feel free to close.

**Comment by DxCx** [comment]
@helfer we can remove it, but then people that needs it will find it hard to find,
i suggest to change it to be a dev dependency,  what do you think?

**Comment by helfer** [comment]
It is already a dev dependency, but I think what you're suggesting is moving it from a peerDependency to a simple dependency. I'd be okay with that.

**Comment by DxCx** [comment]
@helfer, ok, do you want me to create a PR for that?

**Comment by helfer** [comment]
Yes, that would be great if you could! :)

**Comment by xavcz** [comment]
Seems that we can close this 🙂
