### ISSUE TITLE
The Whole Thing Needs More Commentary

### ISSUE THREAD

**Issue by wraybowling** [apollographql/meteor-starter-kit#33]
Hello, actual "starter" here. What the heck is this? What does `'graphql-tag'` do? What does `JSON.stringify(currentUser, null, 2)` do? Why is the schema an array with backticks? How does it get turned into an actual database? What kind of database is it? I guess Mongo since that's still inside of .meteor/packages. How does this thing work? Even if this is a 0.1.x release, I think what it needs the most is some commentary. Creators of this, add some comments! Include links to docs. Help a starter like me connect the dots. It's rough down here for us starters.

**Comment by PazzaVlad** [comment]
Yeah it's not so easy to figure out how even this simple example works...

**Comment by Morganjackson** [comment]
@wraybowling have you read http://dev.apollodata.com/core/meteor.html ?

**Comment by stubailo** [comment]
I think this is intended to be more of a project boilerplate, not an educational tool. We're going to look into better learning materials soon but the docs are the best we have right now.

**Comment by jaredtmartin** [comment]
Yeah, I think it's complicated by the fact that the User collection is included in the context, and not really a "normal" collection.  
I'd love to see the classic todos app demonstrated a simple collection accessed via apollo with react.  Another important thing that is missing here is a simple Mutation how to add and edit posts.

**Comment by xavcz** [comment]
Just opened an issue #45 to discuss how to improve this boilerplate, to make it clearer and showcase more neat Apollo features. Feel free to tackle one of the proposed subjects with a pull request 👍

If you struggle to implement what you are working on to improve the boilerplate, open a "wip" pull request and the community will be glad to help you sort it out!

There are simple things to tackle if you take the documentation aside:
- Meteor: http://dev.apollodata.com/core/meteor.html
- React: http://dev.apollodata.com/react/

There is also a codebase tour of the `meteor/apollo` package to help you understanding what's going on under the hood: https://www.codetours.xyz/tour/xavcz/meteor-apollo-codetour
