### ISSUE TITLE
Is ready to production?

### ISSUE THREAD

**Issue by jdnichollsc** [apollographql/meteor-starter-kit#40]
Hi guys, thanks for your work!

One question, is **Apollo + Meteor** ready to Production? Any examples using other databases different to **MongoDB**?

Thanks in advance, Nicholls

**Comment by jaredtmartin** [comment]
You can get examples of using different databases and even multiple databases in a single project here: http://dev.apollodata.com/core/index.html#Meteor-Examples

**Comment by xavcz** [comment]
Yes it its 💯 

More and more apps are using Apollo & Meteor 👍 

You can check the new docs here: http://dev.apollodata.com/core/meteor.html
