### ISSUE TITLE
Client tries to connect to http://localhost.com/graphql when deployed

### ISSUE THREAD

**Issue by purplecones** [apollographql/meteor-starter-kit#44]
[https://meteor-starter-kit-gwzejmvzfx.now.sh/](https://meteor-starter-kit-gwzejmvzfx.now.sh/)

![meteor_apollo_boilerplate](https://cloud.githubusercontent.com/assets/136654/22851315/aa15c476-efeb-11e6-9a01-5ab6702a48ea.png)

**Comment by purplecones** [comment]
ah, I think this is using ROOT_URL correct?

**Comment by purplecones** [comment]
works on aliased `now` deployments [https://mj-test1.now.sh/](https://mj-test1.now.sh/)

needed to deploy like this:
```
meteor-now -e ROOT_URL=https://mj-test1.now.sh --alias mj-test1
```

Looks like [meteor-integration](https://github.com/apollographql/meteor-integration) is not going to work with `now`'s unique URLs.

**Comment by purplecones** [comment]
@lorensr can the apollo client point to `/graphql` without relying on the `ROOT_URL` variable?

**Comment by xavcz** [comment]
When specifying the `uri` the Apollo Client will send queries to, we are using `Meteor.absoluteUrl(path)`.

The `apollo` meteor package could provide some warning if the `ROOT_URL` is not configured? And patch it in the same move? 

Looking at [the docs of `Meteor.absoluteUrl()`](https://docs.meteor.com/api/core.html#Meteor-absoluteUrl), we can use the `rootUrl` option.

> Override the default ROOT_URL from the server environment. For example: "http://foo.example.com"

```js
// provide the right uri to query by the Apollo Client
const getRootUrl = () => {
  if (typeof window !== 'undefined') {
    
    const rootUrlSimilarToAbsolute = `${window.location.origin}/`;
    
    // is the client trying to access 'http://1.2.3.4:3000/',
    // but the Meteor.absoluteUrl() is 'http://localhost:3000/'?
    if (rootUrlSimilarToAbsolute !== Meteor.absoluteUrl()) {
      console.warn("[Apollo Meteor Integration] It looks like you didn't define correctly the ROOT_URL env variable when deploying your app. We have patched it for you, but it's not a reliable solution. We would advice you to re-deploy with a ROOT_URL env variable set correctly.");
      
      return rootUrlSimilarToAbsolute;
    }
    
  }
  
  return Meteor.absoluteUrl();
};
```

And so further in `createMeteorNetworkInterface`:
```js
let interfaceOptions = {
  uri: Meteor.absoluteUrl(path, {rootUrl: getRootUrl()}),
};
```

We have been facing the same issue in Telescope Nova and provided a similar work-around: https://github.com/TelescopeJS/Telescope/issues/1554

Would this modification deserve a PR on the meteor-integration?

**Comment by lorensr** [comment]
Does relative work? uri: '/graphql' ?

**Comment by stubailo** [comment]
We could use `/graphql` on the client, but that won't work if you are doing SSR since there are no relative URLs on the server.

Honestly I think you'll experience a lot of problems with Meteor if you don't set ROOT_URL properly - maybe we should just have some kind of error if that is not set.

**Comment by purplecones** [comment]
Even though I set the `uri` to be `window.location.origin + '/graphql'`, it still points to `ROOT_URL` + `'/graphql'`. What gives?

```
console.log({
  origin: window.location.origin,
  absoluteUrl: Meteor.absoluteUrl()
});
const url = window.location.origin + '/graphql';
console.log({url});
const client = new ApolloClient(meteorClientConfig({
  uri: url,
}));
```
https://meteor-starter-kit-acwtzkksqt.now.sh/

**Comment by xavcz** [comment]
It's because the `meteorClientConfig` doesn't take care of any `uri` param. You can test this by cloning the package in a root folder named `/packages` and the uri there directly: https://github.com/apollographql/meteor-integration/blob/master/main-client.js#L29-L31 

However you'll need to check that `window` is defined because `meteorClientConfig` is exported server-side.

**Comment by xavcz** [comment]
You can now pass a specific uri to `createMeteorNetworkInterface`: 

```js
const networkInterface = createMeteorNetworkInterface({ uri: 'https://some-meteor-app.com/graphql' });

const client = new ApolloClient(meteorClientConfig({ networkInterface });
```

Here are some more infos: http://dev.apollodata.com/core/meteor.html#createMeteorNetworkInterface

Closing 👍
