### ISSUE TITLE
can't get this to render 

### ISSUE THREAD

**Issue by frankwo1** [apollographql/meteor-starter-kit#50]
Hi,
Can you look at this - using the model mentioned by DBX834 - I cannot get it to render second page

const AppRoutes = {
  path: '/', component: App1,
  indexRoute: { component: App1 },
  childRoutes: { name: 'dep', path:'dep', component: App }
};

Meteor.startup(() => {
  render(
    <ApolloProvider client={client}>
      <Router routes={AppRoutes} history={browserHistory} />
    </ApolloProvider>,
    document.getElementById('app')
  );
});
Frank

**Comment by xavcz** [comment]
Can you provide a simple reproduction as a repository please? 

I don't get your code neither the model you mention.

**Comment by frankwo1** [comment]
Hi Xavier, I was trying to replicate this since I'm using Apollo & react
https://github.com/apollographql/meteor-starter-kit/issues/20

Did not use the correct syntax for this part
const AppRoutes = {
  path: '/',
  component: /* App Component */,
  indexRoute: { component: /* Homepage Component */ },
  childRoutes: /* Child Routes */,
};

**Comment by xavcz** [comment]
The code is using an old API of react router. Without a repo to reproduce I can't do much for you.

**Comment by frankwo1** [comment]
No problem - I was trying to see if this code might work and it doesn't anymore - no reason to spend anymore time on this Thanks
