### ISSUE TITLE
How to create meteor+apollo app with realtime updates?

### ISSUE THREAD

**Issue by raisudeen** [apollographql/meteor-starter-kit#7]
Hi @stubailo ,

First of all, Tons of thanks for this awesome framework. One of my dream is Meteor+SQL.

I used to watch this project for a couple of weeks. I was working on a fun project on top of Meteor for last 3 months. But i stopped it only because of lack of relational queries in MongoDB. Then, I came to know about ApolloStack. I watched your webinr today(27/04/2016) at MeteorNight, and tried the Demo App you provided. But the App is not updating the data realtime. I tried to add "autopublish" module, but still it is not working. Most of them using Meteor mainly for Realtime updates. As Im new to Apollo (not only me), Im bit confused on implementing it. Can you please post a complete working demo TODO Meteor app (like the [Tutorial in Meteor](https://www.meteor.com/tutorials/react/creating-an-app)) having Meteor+Mysql/PG+ApolloStack+Pub/Sub?

Thanks alot in advance.
-Raisudeen.

**Comment by stubailo** [comment]
Realtime updates are currently not supported. What kinds of requirements for reactivity do you have?

**Comment by raisudeen** [comment]
@stubailo I expect that whenever I add/update/delete  a "Todo" Item, it should get reflected for all other users using Pub/Sub. i.e, Ability to publish mutation results to subscribed users.

**Comment by stubailo** [comment]
@raisudeen for pub/sub related features, Meteor is still the best choice. You can use Apollo for your non-reactive data and Meteor subscriptions for reactivity in the same app!

As mentioned in some of our blog posts, we are intentionally not focusing on this type of reactivity to start with, although we expect to have some simple solutions soon like https://github.com/apollostack/apollo-client/pull/153

**Comment by stubailo** [comment]
So to answer your original question, I think the way to do that is to use Meteor's `createContainer` and Apollo `connect` together. So the Meteor one injects the data from Mongo, which is reactive, and the Apollo one can use that to do a static query which can fetch from any data source - SQL, etc.

**Comment by raisudeen** [comment]
@stubailo Thanks alot. "Polling" looks like a simple way to do it. I will try my level best to implement it. Between, You guys are doing Great job. I expect more updates from ApolloStack. 👍

**Comment by jsumanth5526** [comment]
We can use Mysql packages like numtel:mysql , nodets:mysql in meteor and use wamp server for to have meteor with MySQL database right ?

**Comment by jvallarvisp** [comment]
Hi @stubailo, I have been this meteor starter kit. One of our requirements for reactivity is to use subscriptions in React. 
I found this non-Meteor implementation of Subscriptions 
https://github.com/sysgears/apollo-fullstack-starter-kit

I am new to Apollo and still learning. It would be great if you guys can integrate subscriptions to this meteor starter kit. Thanks a lot.

**Comment by xavcz** [comment]
Hey folks!

There are now several ways to control the reactivity, I'm pointing you out to the docs that will be better than a long speech ☺️

Via polling / refetch or subscriptions: http://dev.apollodata.com/react/receiving-updates.html
By controlling the store: http://dev.apollodata.com/react/cache-updates.html

Subscriptions are now on their way to be implemented out of the box in `meteor/apollo` (opened PR), we may end up showcasing them here.

And you can of course still use Meteor data layer alongside with Apollo 👍
